Fixed ci handling failure

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -67,13 +67,21 @@ jobs:
           name: check if validate action does not fail and does not produce any diff
           command: |
             ./gradlew validateLicenseList
-            [[ -z "$(git diff --name-only -- app)" ]]
+
+            if ! [[ -z "$(git diff --name-only -- app)" ]]; then
+              echo "diff has been generated. validate logic must not generate any diff."
+              exit 1
+            fi
 
       - run: 
           name: check if init action does not fail and does not produce any diff
           command: |
             ./gradlew initLicenseList -Poverwrite=true
-            [[ -z "$(git diff --name-only -- app)" ]]
+
+            if ! [[ -z "$(git diff --name-only -- app)" ]]; then
+              echo "diff has been generated. assemble logic might be changed and it would be a breaking change."
+              exit 1
+            fi
       - run:
           name: check if ignore file works
           command: |
@@ -85,7 +93,10 @@ jobs:
             fi
 
             ./gradlew initLicenseList -Poverwrite=true
-            diff app/artifact-definition.yml fixtures/nothing-ignored-artifact-definition.yml
+            if ! diff app/artifact-definition.yml fixtures/nothing-ignored-artifact-definition.yml; then
+              echo "diff has not been generated. .customartifactignore might be wrong or artifact-definition is wrong"
+              exit 1
+            fi
 
             git checkout -- app
       - run: 
@@ -102,24 +113,35 @@ jobs:
             fi
 
             # Create a patch to see how manual modification happens on fixtures/license-catalog.yml
-            diff -u fixtures/artifact-definition.yml fixtures/merge-artifact-definition.yml > fixtures/current-state-base.patch
+            if diff -u fixtures/artifact-definition.yml fixtures/merge-artifact-definition.yml > fixtures/current-state-base.patch; then
+              echo "diff could not be generated"
+              exit 1
+            fi
 
             cp -f fixtures/merge-artifact-definition.yml app/artifact-definition.yml
             cp -f fixtures/merge-license-catalog.yml app/license-catalog.yml
 
             ./gradlew mergeLicenseList
 
-            # Check if merge process could preserve license-catalog.yml
-            diff app/license-catalog.yml fixtures/merge-license-catalog.yml
+            if ! diff app/license-catalog.yml fixtures/merge-license-catalog.yml; then
+              echo "merge process could not preserve license-catalog"
+              exit 1
+            fi
 
             # As for artifact-definition.yml, removed artifacts should be reverted so diff must be generated
-            ! diff app/artifact-definition.yml fixtures/merge-artifact-definition.yml
+            if diff app/artifact-definition.yml fixtures/merge-artifact-definition.yml; then
+              echo "No diff is available. merge process should revert changes so diff is expected."
+              exit 1
+            fi
 
             # Generated diff should be same to the merge result above
             patch -fu app/artifact-definition.yml < fixtures/current-state-base.patch
 
             # Should be reverted to fixtures/merge-artifact-definition.yml
-            diff fixtures/merge-artifact-definition.yml app/artifact-definition.yml
+            if ! diff fixtures/merge-artifact-definition.yml app/artifact-definition.yml; then
+              echo "diff hapenned. no diff is expected"
+              exit 1
+            fi
       # TODO snapshot tests provided by espresso
       - save_gradle_cache:
           cache_name: example
